addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
  - addresses:
      - 192.168.0.10
    conditions:
      ready: true
kind: EndpointSlice
metadata:
  labels:
    kubernetes.io/service-name: lab
  name: lab
  namespace: external
ports:
  - name: https
    port: 443
