apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab
  namespace: external
spec:
  ingressClassName: traefik
  rules:
    - host: lab.cdbrdr.com
      http:
        paths:
          - backend:
              service:
                name: lab
                port:
                  name: https
            path: /
            pathType: Prefix
